
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xb7\xb0\xe7\x8cZ\xc5\xcc\xb3\xed3\xa1hb;\xe8\xf4'
    
_lr_action_items = {'LLAVE_L':([0,],[1,]),'COMA':([4,],[6,]),'LLAVE_R':([3,4,7,],[5,-2,-3,]),'NUMERO':([1,6,],[4,4,]),'$end':([2,5,],[0,-1,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'numeros':([1,6,],[3,7,]),'lista':([0,],[2,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> lista","S'",1,None,None,None),
  ('lista -> LLAVE_L numeros LLAVE_R','lista',3,'p_lista','/home/rgoro/facu/tleng/tleng_tp2/test/parser_rules.py',9),
  ('numeros -> NUMERO','numeros',1,'p_numeros_numero','/home/rgoro/facu/tleng/tleng_tp2/test/parser_rules.py',19),
  ('numeros -> NUMERO COMA numeros','numeros',3,'p_numeros_coma','/home/rgoro/facu/tleng/tleng_tp2/test/parser_rules.py',23),
]
