#!/bin/sh
echo "ej1"
./hacer_midi.sh ej1
echo "ej2"
./hacer_midi.sh ej2
echo "ej3"
./hacer_midi.sh ej3
echo "ej4"
./hacer_midi.sh ej4
echo "jijiji"
./hacer_midi.sh jijiji
echo "post_crucifixion_riff"
./hacer_midi.sh post_crucifixion_riff
echo "4\:33"
./hacer_midi.sh 4\:33
echo "erroneo_1"
./hacer_midi.sh erroneo_1
echo "erroneo_2"
./hacer_midi.sh erroneo_2
echo "erroneo_3"
./hacer_midi.sh erroneo_3
echo "erroneo_4"
./hacer_midi.sh erroneo_4
echo "erroneo_5"
./hacer_midi.sh erroneo_5
echo "erroneo_6"
./hacer_midi.sh erroneo_6
echo "erroneo_7"
./hacer_midi.sh erroneo_7
echo "erroneo_8"
./hacer_midi.sh erroneo_8
echo "erroneo_9"
./hacer_midi.sh erroneo_9
